version: "3.7"

services:
        nginx:
                depends_on: 
                        - wordpress
                build: ./requirements/nginx
                networks:
                        - bonjour
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/var/www/wordpress
                restart: always

        wordpress:
                depends_on: 
                        - mariadb
                build: ./requirements/wordpress
                networks:
                        - bonjour
                volumes:
                        - wordpress:/var/www/wordpress
                environment:
                        - SQL_NAME=${SQL_NAME}
                        - SQL_USER=${SQL_USER}
                        - SQL_PASS=${SQL_PASS}
                        - SQL_HOST=${SQL_HOST}
                        - DOMAIN_NAME=${DOMAIN_NAME}
                        - WP_TITLE=${WP_TITLE}
                        - WP_MAIL=${WP_MAIL}
                restart: always

        mariadb:
                build: 
                        context: ./requirements/mariadb
                        args:
                                - SQL_NAME=${SQL_NAME}
                                - SQL_USER=${SQL_USER}
                                - SQL_PASS=${SQL_PASS}
                                - SQL_ROOTPASS=${SQL_ROOTPASS}
                networks:
                        - bonjour
                volumes:
                        - mariadb:/var/lib/mysql
                restart: always

networks:
        bonjour:
                name: incepstonks

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/leickmay/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/leickmay/data/mariadb
                        o: bind
                        type: none

