CREATE DATABASE SQL_NAME;
CREATE USER 'SQL_USER'@'%' IDENTIFIED BY 'SQL_PASS';
GRANT ALL PRIVILEGES ON SQL_NAME.* TO 'SQL_USER'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'SQL_ROOTPASS';
